<?php

/**
 * @file
 * Intranet core module.
 */

/**
 * Implements hook_theme().
 */
function intranet_core_theme($existing, $type, $theme, $path) {
  return [
    'logo_dimar_block' => [
      'variables' => [
        'image' => NULL,
      ],
      'render element' => 'children',
    ],
    'logo_defensa_block' => [
      'variables' => [
        'image' => NULL,
      ],
      'render element' => 'children',
    ],
  ];
}
